namespace SangoUtils.UnitySourceGenerators.Utils
{
    internal sealed class Def
    {
        public const string Dom_Generateds = "SangoUtils.UnitySourceGenerators.Generateds";
        public const string Dom_Declaration = "/// <summary>\r\n/// This is Generated by a Tools, you should avoid make direct modify it.\r\n/// </summary>\r\n";
    }
}
