namespace SangoUtils.UnitySourceGenerators.Utils
{
    internal sealed class Def
    {
        public const string Dom_Generateds = "SangoUtils.UnitySourceGenerators.Generateds";
        public const string Dom_System = "System";
        public const string Dom_UnityEngine = "UnityEngine";
        public const string Dom_UnityEditor = "UnityEditor";
        public const string Dom_Unity = "Unity";
        public const string Dom_UnityEvents = "UnityEngine.Events";
        public const string Dom_Declaration = "/// <summary>\r\n/// This is Generated by a Tools, you should avoid make direct modify it.\r\n/// </summary>\r\n";

        public const string Op_Equal = "=";
        public const string Op_NotEqual = "!=";
        public const string Op_LessThan = "<";
        public const string Op_GreaterThan = ">";

        public const string Sym_Colon = ":";
        public const string Sym_Semicolon = ";";
        public const string Sym_Underline = "_";
        public const string Sym_Not = "!";
        public const string Sym_Dot = ".";
        public const string Sym_Slash = "/";
        public const string Sym_Percent = "%";
        public const string Sym_Open = "(";
        public const string Sym_Close = ")";

        public const string Fil_Space = " ";
        public const string Fil_Tab = "\t";
        public const string Fil_Line = "\n";

        public const string Quo_Double = "\"";
        public const string Quo_Single = "\'";

        public const string Key_Namespace = "namespace";
        public const string Key_Attribute = "Attribute";
        public const string Key_Public = "public";
        public const string Key_Private = "private";
        public const string Key_Internal = "internal";
        public const string Key_Static = "static";
        public const string Key_Void = "void";
        public const string Key_Const = "const";
        public const string Key_Where = "where";
        public const string Key_New = "new";
        public const string Key_Partial = "partial";
        public const string Key_Using = "using";
        public const string Key_Event = "event";
        public const string Key_Action = "Action";
        public const string Key_UnityEvent = "UnityEvent";

        public const string Atr_SerializeField = "[SerializeField]";

        public const string Typ_Int = "int";
        public const string Typ_String = "string";
        public const string Typ_Float = "float";
        public const string Typ_Long = "long";

        public const string Ext_gcs = ".g.cs";
    }
}
